### PR TITLE
[#156996834] Prepare Logstash filters for Logit

### PR DESCRIPTION
**Pull request by bandesz**
## What

Most of these changes were accepted upstream when we did the spike but not included in gds_master.

## How to review

 - Basic code review. The changes were already accepted upstream.
 - Review as part of https://github.com/alphagov/paas-cf/pull/1360 and https://github.com/alphagov/paas-bootstrap/pull/163

## Who can review it

Not @bandesz or @keymon

### CODE REVIEW

**Comment by alext** [comment]
I'm going to close this for now. We can reopen and pick up the review of this when we start work on https://www.pivotaltracker.com/story/show/157053149.

**Comment by henrytk** [comment]
The commit "Replace alter filter when processing app logs" is the only one not merged upstream. I could raise a pull request for it, but I don't know why it was added. Can you add a useful commit message please.

**Comment by keymon** [comment]
> The commit "Replace alter filter when processing app logs" is the only one not merged upstream. I could raise a pull request for it, but I don't know why it was added. Can you add a useful commit message please.

TBH, I do not know neither why that was added. I did not work on that story back then :thinking:, I joined at the end.

But checking the code it seems to be the same implementation, but trying to avoid use `coalesce` and not deleting `[parsed_json_field][event_type]`. 

My guess is that the previous approach was causing some kind of error, but I am not sure why it was added at all

**Comment by henrytk** [comment]
I've edited the commit message to make it consistent with the other similar commits:

```
We want to avoid installing a 3rd party filter plugin and the effect can be
easily achieved with built-in constructs.
```

I'll raise a pull request upstream.

**Update:** done: https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/300

**Pull request merged**
